name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ['v*']
    pull_request: [main]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_simple:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: 'nubia'
      image_name: 'juno'
      push: ${{ github.event_name != 'pull_request' }}
