name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_public_image_simple:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-dockerhub.yaml@main
    with:
      repo_name: 'nubia'
      image_name: 'juno'
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
