name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_complete:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-dockerhub.yaml@main
    with:
      # By default it pushes it to nethermindeth, which is a test repo
      # in dockerhub.  If you want to push to a different repo, you can
      # set this value.
      repo_name: 'nethermindeth'

      # By default it uses the repository name as the image name
      image_name: '<repository-name>'

      # By default latest and the git sha are added
      # Use this if you want something custom, for example a semver.
      additional_tags: ''

      platforms: 'linux/amd64,linux/arm64'
      context: '.'
      setup-qemu: false
      dockerfile_path: 'Dockerfile'
      docker_secrets: ''
      docker_secret_envs: ''
      docker_secret_files: ''
      docker_ulimit: ''
      docker_build_args: ''
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
