name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_service_a:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "nubia"
      image_name: "juno"
      context: "service_a/"
      dockerfile_path: "service_a/Dockerfile"

  build_service_b:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@main
    with:
      group_name: "nubia"
      image_name: "juno"
      context: "service_b/"
      dockerfile_path: "service_b/Dockerfile"
