name: Docker Image Promotion

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        type: choice
        options: ['staging', 'prod']
        required: true
      tags:
        description: 'Tags to promote (comma-separated)'
        type: string
        required: false
        default: 'latest'

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  promote:
    uses: NethermindEth/github-workflows/.github/workflows/promote-docker.yaml@feat/docker-image-workflow
    with:
      # Required inputs:
      jfrog_url: 'nethermind.jfrog.io'  # URL of Artifactory server
      target_env: ${{ inputs.target_env }}  # Target environment (staging/prod)
      tags: ${{ inputs.tags }}  # Tags to promote

    secrets:
      artifactory_access_token: ${{ secrets.ARTIFACTORY_TOKEN }}  # Required: Token for Artifactory