name: Docker Image Build & Publish

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    uses: NethermindEth/github-workflows/.github/workflows/publish-docker-image.yaml@feat/docker-image-workflow
    with:
      # Required inputs:
      jfrog_url: 'nethermind.jfrog.io'  # default URL of Artifactory server

      # Optional inputs with defaults:
      platforms: 'linux/amd64,linux/arm64'  # Platforms to build for
      dockerfile_path: 'Dockerfile'  # Path to Dockerfile
      additional_tags: ${{ github.ref_type == 'tag' && github.ref_name || '' }}  # Additional tags to apply

    secrets:
      artifactory_access_token: ${{ secrets.ARTIFACTORY_TOKEN }}  # Required: Token for Artifactory