name: "Build and publich to dockerhub"

description: "Build and publich to dockerhub"
author: "derrix060"

inputs:
  build-args:
    description: "List of build-time variables"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  file:
    description: "Path to the Dockerfile"
    required: false
  platforms:
    description: "List of target platforms for build"
    required: false
  secrets:
    description: "List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
    required: false
  setup-qemu:
    description: "Set up QEMU"
    required: false
    default: false
  tags:
    description: "List of tags"
    required: false

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: NethermindEth/github-workflows/.github/actions/build-and-push@mario/fix-terraform-checks
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        secrets: ${{ inputs.secrets }}
        setup-qemu: ${{ inputs.setup-qemu }}
        tags: ${{ inputs.tags }}
