name: "Build and publich to dockerhub"

description: "Build and publich to dockerhub"
author: "derrix060"


inputs:
  build-args:
    description: "List of build-time variables"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  file:
    description: "Path to the Dockerfile"
    required: false
  platforms:
    description: "List of target platforms for build"
    required: false
  secrets:
    description: "List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
    required: false
  setup-qemu:
    description: "Set up QEMU"
    required: false
    default: false
  tags:
    description: "List of tags"
    required: false

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      if: ${{ inputs.setup-qemu }}
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        secrets: ${{ inputs.secrets }}
        tags: ${{ inputs.tags }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ steps.build.outputs.imageid }}
        exit-code: '1'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
        TRIVY_DISABLE_VEX_NOTICE: true

    # TODO: add Attestation and Summary
