name: Docker Build and Push

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_private_image:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push.yaml@main
    with:
      # Optional inputs (with their defaults shown)
      artifactory_url: 'nethermind.jfrog.io'
      image_name: '<repository-name>'
      platforms: 'linux/amd64,linux/arm64'
      context: '.'
      setup-qemu: false
      dockerfile_path: 'Dockerfile'
      additional_tags: ''                      # Example: 'latest,1.0.0'
      # Required Inputs
      group_name: ''  # For example kyoto, nubia, angkor, etc

  build_public_image:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push.yaml@main
    with:
      # Optional inputs (with their defaults shown)
      image_name: '<repository-name>'
      platforms: 'linux/amd64,linux/arm64'
      context: '.'
      setup-qemu: false
      dockerfile_path: 'Dockerfile'
      additional_tags: ''                      # Example: 'latest,1.0.0'
      # Required Inputs
      is_public_image: true
      dockerhub_repo: 'nethermindeth'  # Default value
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
