name: Docker Image Promotion

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        type: choice
        options: ['staging', 'prod']
        required: true
      tags:
        description: 'Tags to promote (comma-separated)'
        type: string
        required: true

jobs:
  promote:
    uses: NethermindEth/github-workflows/.github/workflows/promote-docker.yaml@main
    with:
      # Required inputs (with defaults):
      jfrog_url: 'nethermind.jfrog.io'        # Required: URL of Artifactory server (default: nethermind.jfrog.io)
      # Required inputs:
      target_env: ${{ inputs.target_env }}     # Required: Target environment (staging/prod)
      tags: ${{ inputs.tags }}                 # Required: Tags to promote
    
    secrets:
      artifactory_access_token: ${{ secrets.ARTIFACTORY_TOKEN }}  # Required: Token for Artifactory