# Builds and publishes Docker images to JFrog Artifactory
# Features:
# - Multi-platform build support (amd64/arm64)
# - Vulnerability scanning with Trivy
# - Build provenance attestation
# - Configurable build context and Dockerfile path
# - Automated builds on main branch and tags
name: Docker Image Build & Publish

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    uses: NethermindEth/github-workflows/.github/workflows/publish-docker.yaml@main
    with:
      # Optional inputs (with their defaults shown)
      jfrog_url: 'nethermind.jfrog.io'
      image_name: '<repository-name>'
      group_name: '<nethermind group name>'    # Example: kyoto, nubia, etc
      platforms: 'linux/amd64,linux/arm64'
      context: '.'
      setup-qemu: false
      dockerfile_path: 'Dockerfile'
      additional_tags: ''                      # Example: 'latest,1.0.0'
      docker_secrets: ''
      docker_secret_envs: ''
      docker_secret_files: ''
      docker_ulimit: ''
      docker_build_args: ''
