# Builds and publishes Docker images to JFrog Artifactory
name: Docker Image Build & Publish

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_private_service:
    uses: NethermindEth/github-workflows/.github/workflows/publish-docker.yaml@main
    with:
      image_name: 'service-a'
      group_name: 'kyoto'
      context: 'service_a/'
      dockerfile_path: 'service_a/Dockerfile'

  build_public_service:
    uses: NethermindEth/github-workflows/.github/workflows/publish-docker.yaml@main
    with:
      is_public_image: true
      image_name: 'service-b'
      dockerhub_repo: 'nethermindeth'  # Default value
      context: 'service_b/'
      dockerfile_path: 'service_b/Dockerfile'
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
