name: Docker Image Build & Publish

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

permissions:
  id-token: write
  attestations: write
  contents: read

# Note: Build process includes:
# 1. Build image without pushing
# 2. Run Trivy vulnerability scan
# 3. Push to registry if scan passes
# 4. Create and upload attestation
jobs:
  build:
    uses: NethermindEth/github-workflows/.github/workflows/publish-docker.yaml@main
    with:
      # Required inputs (with defaults):
      jfrog_url: 'nethermind.jfrog.io'         # Required: URL of Artifactory server (default: nethermind.jfrog.io)
      platforms: 'linux/amd64,linux/arm64'     # Required: Platforms to build for (default: linux/amd64,linux/arm64)
      dockerfile_path: 'Dockerfile'            # Required: Path to Dockerfile (default: Dockerfile)
      # Optional inputs:
      additional_tags: ''                      # Optional: Additional tags to apply
    secrets:
      artifactory_access_token: ${{ secrets.ARTIFACTORY_TOKEN }}  # Required: Token for Artifactory