on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.access-token }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.access-token }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
