on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true
    outputs:
      version:
        description: "Computed repository version"
        value: ${{ jobs.bump_version.outputs.version }}

jobs:
  bump_version:
    name: "Bump version and create changelog with commitizen"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.access-token }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.access-token }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
