on:
  workflow_call:
    inputs:
      runner:
        description: "Runner to use"
        type: string
        required: false
        default: "ubuntu-latest"
      git_repository:
        description: "Name of the git repository to checkout and build from"
        type: string
        required: false
        default: ${{ github.repository }}
      git_ref:
        description: "Git reference to checkout"
        type: string
        required: false
        default: ''
      checkout_submodules:
        description: "Check out submodules type.  Defaults to recursive"
        type: string
        required: false
        default: "recursive"
      repo_name:
        description: "Name of the repository to publish to"
        type: string
        required: false
        default: ""
      jfrog_url:
        description: "URL of Artifactory server"
        type: string
        default: "nethermind.jfrog.io"
        required: false
      image_name:
        description: "Name of the image to publish.  Defaults to the repository name."
        type: string
        required: false
        default: "${{ github.event.repository.name }}"
      group_name:
        description: "Name of the group in Nethermind.  Example: nubia, kyoto, etc"
        type: string
        required: false
        default: ""
      push:
        description: "Whether or not to push to Artifactory"
        type: boolean
        default: true
        required: false
      context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        type: string
        default: "."
        required: false
      pre_build_script:
        description: "Script to run before the build"
        type: string
        required: false
        default: ""
      platforms:
        description: "Platforms to build for (comma-separated)"
        type: string
        default: "linux/amd64,linux/arm64"
        required: false
      fetch-depth:
        description: "Fetch depth"
        type: number
        required: false
        default: 1
      setup-qemu:
        description: "Set up QEMU"
        type: boolean
        default: false
        required: false
      dockerfile_path:
        description: "Path to Dockerfile"
        type: string
        default: "Dockerfile"
        required: false
      additional_tags:
        description: "Additional tags to apply (comma-separated)"
        type: string
        default: ""
        required: false
      docker_secrets:
        description: "List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
        type: string
        required: false
      docker_secret_envs:
        description: "List of secret env vars to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR)"
        required: false
        type: string
      docker_secret_files:
        description: "List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)"
        required: false
        type: string
      docker_ulimit:
        description: "Ulimit options (e.g., nofile=1024:1024)"
        required: false
        type: string
      docker_build_args:
        description: "List of build-time variables"
        required: false
        type: string
      ignore_trivy:
        description: "Ignore Trivy scan errors"
        required: false
        type: boolean
        default: false
      run_trivy:
        description: "Run Trivy scan"
        required: false
        type: boolean
        default: true
    secrets:
      git_token:
        description: "Git token to use for checkout"
        required: false

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.1.1
        with:
          repository: ${{ inputs.git_repository }}
          token: ${{ secrets.git_token || github.token }}
          ref: ${{ inputs.git_ref }}
          submodules: ${{ inputs.checkout_submodules }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set env vars
        id: env-vars
        run: |
          # Set Repo name
          if [[ -n "${{ inputs.repo_name }}" ]]; then
            export REPO_NAME="${{ inputs.repo_name }}"
          elif [[ -n "${{ inputs.group_name }}" ]]; then
            export REPO_NAME="${{ inputs.group_name }}-oci-local-dev"
          else
            echo "Unable to determine the repo name.  Please set either group_name or the repo_name."
            exit 1
          fi

          # Set image name
          echo "IMAGE_NAME=${REPO_NAME}/${{ inputs.image_name }}" >> $GITHUB_OUTPUT

      - name: Install JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ inputs.jfrog_url }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Registry with OIDC
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ inputs.jfrog_url }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}

      - name: Run pre-build script
        if: ${{ inputs.pre_build_script != '' }}
        run: |
          ${{ inputs.pre_build_script }}

      - name: Build and push
        uses: NethermindEth/github-action-image-build-and-push@86f2a3a5f903403ca2608b364f3f2808bf79a838
        with:
          registry: "artifactory"
          image_name: ${{ steps.env-vars.outputs.IMAGE_NAME }}
          image_tags: ${{ inputs.additional_tags }}
          push-to-registry: ${{ inputs.push }}
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.context }}
          dockerfile_path: ${{ inputs.dockerfile_path }}
          setup-qemu: ${{ inputs.setup-qemu }}
          secrets: ${{ inputs.docker_secrets }}
          secret-envs: ${{ inputs.docker_secret_envs }}
          secret-files: ${{ inputs.docker_secret_files }}
          ulimit: ${{ inputs.docker_ulimit }}
          build-args: ${{ inputs.docker_build_args }}
          ignore_trivy: ${{ inputs.ignore_trivy }}
          run_trivy: ${{ inputs.run_trivy }}
