on:
  workflow_call:
    inputs:
      repositoryName:
        description: 'Name of current repository'
        required: true
        type: string
    secrets:
      artifactory_access_token:
        description: 'A token used to communicate with Artifactory'
        required: true

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release.yaml@main
    with:
      releaseType: terraform-module

  compute_name:
    needs: [ release ]
    if: needs.release.outputs.releases_created == 'true'
    uses: ./.github/workflows/compute-terraform-module-name.yaml@main
    with:
      repository_name: ${{ inputs.repositoryName }}

  publish:
    needs: [ release, compute_name ]
    if: needs.release.outputs.releases_created == 'true'
    uses: ./.github/workflows/publish-terraform-module.yaml@main
    with:
      provider_name: ${{ needs.compute_name.outputs.provider_name }}
      module_name: ${{ needs.compute_name.outputs.module_name }}
      module_version: ${{ needs.release.outputs.tag_name }}
    secrets:
      artifactory_access_token: ${{ secrets.artifactory_access_token }}
