name: CI pull request

on:
  workflow_call:
    inputs:
      artifactory_project:
        description: 'Key of the Artifactory project'
        type: string
        required: true
      image_reportory:
        description: 'Repository name'
        type: string
        required: true
      platforms:
        description: 'Comma-separated list of platforms (e.g., linux/amd64,linux/arm64)'
        type: string
        required: true

    secrets:
      registry_username:
        description: 'Username for Artifactory'
        required: true
      registry_password:
        description: 'Password for Artifactory'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Define image tag
        id: set_tag
        run: |
          GITHUB_REPOSITORY=${{ github.repository }}
          IMAGE_NAME=${GITHUB_REPOSITORY#*/}
          HEAD_REF=${{ github.head_ref }}
          HEAD_SLUG=${HEAD_REF//\//-}
          #SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG=${HEAD_SLUG}-${{ github.sha }}
          echo "HEAD_SLUG=${HEAD_SLUG}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Install JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_PROJECT: ${{ inputs.artifactory_project }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JFROG_HOST }}/${{ inputs.image_reportory }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}
#          username: ${{ secrets.registry_username }}
#          password: ${{ secrets.registry_password }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ vars.JFROG_HOST }}/${{ inputs.image_reportory }}/${{ env.IMAGE_NAME }}:latest
            ${{ vars.JFROG_HOST }}/${{ inputs.image_reportory }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: JFrog build add context
        env:
          JFROG_CLI_BUILD_NAME: ${{ env.IMAGE_NAME }}
          JFROG_CLI_BUILD_NUMBER: ${{ env.HEAD_SLUG }}-${{ github.run_number }}
        run: |
          jf rt build-collect-env
          jf rt build-add-git

      - name: JFrog build add images
        env:
          JFROG_CLI_BUILD_NAME: ${{ env.IMAGE_NAME }}
          JFROG_CLI_BUILD_NUMBER: ${{ env.HEAD_SLUG }}-${{ github.run_number }}
        run: |
          # Pull image manifest
          docker manifest inspect ${{ vars.JFROG_HOST }}/${{ inputs.image_reportory }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > manifest.json

          # Iterate over platforms
          platforms=$(echo ${{ inputs.platforms }} | tr ',' ' ')
          for platform in $platforms; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            digest=$(jq -r \
              --arg os "${os}" \
              --arg arch "${arch}" \
              '.manifests[] | select(.platform.os==$os and .platform.architecture==$arch) | .digest' manifest.json)
            echo "${{ vars.JFROG_HOST }}/${{ inputs.image_reportory }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}@${digest}" > image-file
            jf rt build-docker-create --image-file=image-file ${{ inputs.image_reportory }}
          done

      - name: JFrog build publish
        env:
          JFROG_CLI_BUILD_NAME: ${{ env.IMAGE_NAME }}
          JFROG_CLI_BUILD_NUMBER: ${{ env.HEAD_SLUG }}-${{ github.run_number }}
        run: |
          jf rt build-publish
