on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - shell: bash
        name: Install terraform-docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs "$HOME/.local/bin"
          rm terraform-docs.tar.gz
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - shell: bash
        run: |
          echo "$PATH"
          terraform-docs -v
      - uses: pre-commit/action@v3.0.1
