on:
  workflow_call:
    inputs:
      jfrog_url:
        description: "URL of Artifactory server"
        type: string
        default: "https://nethermind.jfrog.io"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@5b06f730cc5a6f55d78b30753f8583454b08c0aa # v4.8.1
        env:
          JFROG_URL: ${{ inputs.jfrog_url }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Python
        uses: actions/setup-python@v6

      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: terraform-docs/terraform-docs
          tag: v0.17.0

      - name: Install tflint
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: terraform-linters/tflint
          tag: v0.55.1

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
