on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@v1.14.0
        with:
          repo: terraform-docs/terraform-docs
          tag: v0.17.0

      - name: Install tflint
        uses: jaxxstorm/action-install-gh-release@v1.14.0
        with:
          repo: terraform-linters/tflint
          tag: v0.55.1

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
