on:
  workflow_call:
    secrets:
      artifactory_access_token:
        description: 'A token used to communicate with Artifactory'
        required: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_nethermind_jfrog_io: ${{ secrets.artifactory_access_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@v2.0.0
        with:
          repo: terraform-docs/terraform-docs
          tag: v0.17.0

      - name: Install tflint
        uses: jaxxstorm/action-install-gh-release@v2.0.0
        with:
          repo: terraform-linters/tflint
          tag: v0.55.1

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
