on:
  workflow_call:
    secrets:
      artifactory_access_token:
        description: 'A token used to communicate with Artifactory'
        required: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_nethermind_jfrog_io: ${{ secrets.artifactory_access_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install terraform-docs
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin" downloads
          curl -Lso ./downloads/terraform-docs.tar.gz \
            https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf downloads/terraform-docs.tar.gz -C downloads
          chmod +x downloads/terraform-docs
          mv downloads/terraform-docs "$HOME/.local/bin/terraform-docs"
          rm -rf downloads

      - name: Install tflint
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin" downloads
          curl -Lso ./downloads/install_linux.sh \
            https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
          TFLINT_INSTALL_PATH="$HOME/.local/bin" bash ./downloads/install_linux.sh
          rm -rf downloads

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
