on:
  workflow_call:
    inputs:
      jfrog_url:
        description: "URL of Artifactory server"
        type: string
        default: "https://nethermind.jfrog.io"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure JFrog CLI
        id: jfrog
        uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        env:
          JFROG_URL: ${{ inputs.jfrog_url }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0

      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: terraform-docs/terraform-docs
          tag: v0.17.0

      - name: Install tflint
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: terraform-linters/tflint
          tag: v0.55.1

      - name: Run pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
