# DEPRECATED: Use docker-promote-jfrog.yaml or docker-promote-dockerhub.yaml instead

on:
  workflow_call:
    inputs:
      jfrog_url:
        description: "URL of Artifactory server"
        type: string
        default: "nethermind.jfrog.io"
        required: false
      image_name:
        description: "Name of the image to publish.  Defaults to the repository name."
        type: string
        required: false
        default: "${{ github.event.repository.name }}"
      context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        type: string
        default: "."
        required: false
      platforms:
        description: "Platforms to build for (comma-separated)"
        type: string
        default: "linux/amd64,linux/arm64"
        required: false
      setup-qemu:
        description: "Set up QEMU"
        type: boolean
        default: false
        required: false
      dockerfile_path:
        description: "Path to Dockerfile"
        type: string
        default: "Dockerfile"
        required: false
      additional_tags:
        description: "Additional tags to apply (comma-separated)"
        type: string
        default: ""
        required: false
      skip_trivy:
        description: "Should trivy scan be skipped. Use on your own risk"
        type: boolean
        default: false
        required: false
      login_with_oidc:
        description: "Login with OIDC.  Set it to true if you want to use OIDC to login to the registry."
        type: boolean
        default: false
        required: false
    secrets:
      artifactory_access_token:
        description: "A token used to communicate with Artifactory"
        required: false
      artifactory_username:
        description: "Username for Artifactory authentication"
        required: false

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        if: ${{ inputs.setup-qemu }}
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Install JFrog CLI
        if: ${{ inputs.login_with_oidc }}
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ inputs.jfrog_url }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Registry
        if: ${{ !inputs.login_with_oidc }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: https://${{ inputs.jfrog_url }}
          username: ${{ secrets.artifactory_username }}
          password: ${{ secrets.artifactory_access_token }}

      - name: Login to Registry with OIDC
        if: ${{ inputs.login_with_oidc }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.jfrog_url }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ inputs.jfrog_url }}/${{ secrets.artifactory_username }}-oci-local-dev/${{ inputs.image_name }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=raw,value=${{ github.ref_type == 'tag' && github.ref_name || '' }},enable=${{ github.ref_type == 'tag' }}
            type=sha
            ${{ inputs.additional_tags != '' && format('type=raw,value={0}', inputs.additional_tags) || '' }}

      - name: Build (no push)
        id: build_no_push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile_path }}
          platforms: ${{ inputs.platforms }}
          push: false
          tags: temporary-tag
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Run Trivy vulnerability scanner
        id: trivy
        if: ${{ !inputs.skip_trivy }}
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # v0.31.0
        with:
          image-ref: ${{ steps.build_no_push.outputs.imageid }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          trivyignores: ./.trivyignore
          output: "trivy-results.txt"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_DISABLE_VEX_NOTICE: true

      - name: Push to Registry
        run: |
          TMP_TAG=temporary-tag
          NEW_TAGS="${{ steps.meta.outputs.tags }}"
          # Process each tag separately by splitting the comma-separated string
          IFS=',' read -ra TAGS <<< "$NEW_TAGS"
          for TAG in "${TAGS[@]}"; do
            if [ -n "$TAG" ]; then
              echo "Creating image with tag: $TAG"
              docker buildx imagetools create -t "$TAG" "$TMP_TAG"
            fi
          done

      - name: Attest
        if: ${{ success() }}
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        id: attest
        with:
          subject-name: ${{ steps.meta.outputs.tags }}
          subject-digest: ${{ steps.build_no_push.outputs.digest }}
          push-to-registry: true

      - name: Summary
        if: always()
        run: |
          echo "### Build status" >> $GITHUB_STEP_SUMMARY
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Build and push successful" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Build failed" >> $GITHUB_STEP_SUMMARY
          fi

          echo "### Image Tags" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r TAG; do
            echo "- $TAG" >> $GITHUB_STEP_SUMMARY
          done
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "### Trivy Scan Output" >> $GITHUB_STEP_SUMMARY
          if [[ -f trivy-results.txt ]]; then
            echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            while IFS= read -r line; do
              if [[ $line == "┌"* ]]; then echo '```' >> $GITHUB_STEP_SUMMARY; fi
              echo "$line" >> $GITHUB_STEP_SUMMARY
              if [[ $line == *"┘" ]]; then echo '```' >> $GITHUB_STEP_SUMMARY; fi
            done < trivy-results.txt
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          else
            echo "No Trivy report found." >> $GITHUB_STEP_SUMMARY
          fi
