on:
  workflow_call:
    inputs:
      is_public_image:
        type: boolean
        default: false
        required: false
      jfrog_url:
        description: "URL of Artifactory server"
        type: string
        default: "nethermind.jfrog.io"
        required: false
      image_name:
        description: "Name of the image to publish.  Defaults to the repository name."
        type: string
        required: false
        default: "${{ github.event.repository.name }}"
      group_name:
        description: "Name of the group in Nethermind.  Example: nubia, kyoto, etc"
        type: string
        required: false
        default: ""
      dockerhub_repo:
        description: "Name of the repository to publish to"
        type: string
        required: false
        default: "nethermindeth"
      context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        type: string
        default: "."
        required: false
      platforms:
        description: "Platforms to build for (comma-separated)"
        type: string
        default: "linux/amd64,linux/arm64"
        required: false
      setup-qemu:
        description: "Set up QEMU"
        type: boolean
        default: false
        required: false
      dockerfile_path:
        description: "Path to Dockerfile"
        type: string
        default: "Dockerfile"
        required: false
      additional_tags:
        description: "Additional tags to apply (comma-separated)"
        type: string
        default: ""
        required: false
      skip_trivy:
        description: "Should trivy scan be skipped. Use on your own risk"
        type: boolean
        default: false
        required: false
      docker_secrets:
        description: "List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
        type: string
        required: false
      docker_secret_envs:
        description: "List of secret env vars to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR)"
        required: false
        type: string
      docker_secret_files:
        description: "List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)"
        required: false
        type: string
      docker_ulimit:
        description: "Ulimit options (e.g., nofile=1024:1024)"
        required: false
        type: string
      docker_build_args:
        description: "List of build-time variables"
        required: false
        type: string

    secrets:
      # DEPRECATED: It's still here so it doesn't break any old pipelines
      # It will be removed in a later stage
      artifactory_access_token:
        description: "A token used to communicate with Artifactory"
        required: false
      artifactory_username:
        description: "Username for Artifactory authentication"
        required: false

      # Required for public images
      dockerhub_username:
        description: "Username for Docker Hub authentication"
        required: false
      dockerhub_password:
        description: "Password for Docker Hub authentication"
        required: false

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: |
          # Set Repo name
          if [[ "${{ inputs.is_public_image }}" ]]; then
            echo "REPO_NAME=${{ inputs.dockerhub_repo }}" >> $GITHUB_ENV
          elif [[ -z "${{ secrets.artifactory_username }}" ]]; then
            echo "REPO_NAME=${{ secrets.artifactory_username }}-oci-local-dev" >> $GITHUB_ENV
          elif [[ -z "${{ inputs.group_name }}" ]]; then
            echo "REPO_NAME=${{ inputs.group_name }}-oci-local-dev" >> $GITHUB_ENV
          else
            echo "Unable to determine the repo name.  Please set the group_name input if you are using a private image or the repo_name input if you are using a public image."
            exit 1
          fi

          # Set image name
          IMAGE_NAME=${{ env.REPO_NAME }}/${{ inputs.image_name }}
          if [[ "${{ inputs.is_public_image }}" ]]; then
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=${{ inputs.jfrog_url }}/${IMAGE_NAME}" >> $GITHUB_ENV
          fi


      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        if: ${{ inputs.setup-qemu }}
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Install JFrog CLI
        if: ${{ !inputs.is_public_image }}
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ inputs.jfrog_url }}
        with:
          oidc-provider-name: github-nethermindeth

      - name: Login to Registry with OIDC
        if: ${{ !inputs.is_public_image }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.jfrog_url }}
          username: ${{ steps.jfrog.outputs.oidc-user }}
          password: ${{ steps.jfrog.outputs.oidc-token }}

      - name: Login to Docker Hub
        if: ${{ inputs.is_public_image }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_password }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=raw,value=${{ github.ref_type == 'tag' && github.ref_name || '' }},enable=${{ github.ref_type == 'tag' }}
            type=sha
            ${{ inputs.additional_tags != '' && format('type=raw,value={0}', inputs.additional_tags) || '' }}

      - name: Build (no push)
        id: build_no_push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile_path }}
          platforms: ${{ inputs.platforms }}
          push: false
          tags: temporary-tag
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          secrets: ${{ inputs.docker_secrets }}
          secret-envs: ${{ inputs.docker_secret_envs }}
          secret-files: ${{ inputs.docker_secret_files }}
          ulimit: ${{ inputs.docker_ulimit }}
          build-args: ${{ inputs.docker_build_args }}

      - name: Run Trivy vulnerability scanner
        id: trivy
        if: ${{ !inputs.skip_trivy }}
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          image-ref: ${{ steps.build_no_push.outputs.imageid }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          trivyignores: ./.trivyignore
          output: "trivy-results.txt"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_DISABLE_VEX_NOTICE: true

      - name: Push to Registry
        run: |
          TMP_TAG=temporary-tag
          NEW_TAGS="${{ steps.meta.outputs.tags }}"
          # Process each tag separately by splitting the comma-separated string
          IFS=',' read -ra TAGS <<< "$NEW_TAGS"
          for TAG in "${TAGS[@]}"; do
            if [ -n "$TAG" ]; then
              echo "Creating image with tag: $TAG"
              docker buildx imagetools create -t "$TAG" "$TMP_TAG"
            fi
          done

      - name: Attest
        if: ${{ success() }}
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        id: attest
        with:
          subject-name: ${{ steps.meta.outputs.tags }}
          subject-digest: ${{ steps.build_no_push.outputs.digest }}
          push-to-registry: true

      - name: Summary
        if: always()
        run: |
          echo "### Build status" >> $GITHUB_STEP_SUMMARY
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Build and push successful" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Build failed" >> $GITHUB_STEP_SUMMARY
          fi

          echo "### Image Tags" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r TAG; do
            echo "- $TAG" >> $GITHUB_STEP_SUMMARY
          done
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "### Trivy Scan Output" >> $GITHUB_STEP_SUMMARY
          if [[ -f trivy-results.txt ]]; then
            echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            while IFS= read -r line; do
              if [[ $line == "┌"* ]]; then echo '```' >> $GITHUB_STEP_SUMMARY; fi
              echo "$line" >> $GITHUB_STEP_SUMMARY
              if [[ $line == *"┘" ]]; then echo '```' >> $GITHUB_STEP_SUMMARY; fi
            done < trivy-results.txt
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          else
            echo "No Trivy report found." >> $GITHUB_STEP_SUMMARY
          fi
