on:
  workflow_call:
    inputs:
      jfrog_url:
        description: 'URL of Artifactory server'
        type: string
        default: 'https://nethermind.jfrog.io'
      platforms:
        description: 'Platforms to build for (comma-separated)'
        type: string
        default: 'linux/amd64,linux/arm64'
      dockerfile_path:
        description: 'Path to the Dockerfile'
        type: string
        default: 'Dockerfile'
      promotion_type:
        description: 'Type of promotion (to-staging/to-prod)'
        type: string
        required: false
      source_tag:
        description: 'Specific tag to promote'
        type: string
        required: false
    secrets:
      artifactory_access_token:
        description: 'A token used to communicate with Artifactory'
        required: true

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Group Topic
        id: topics
        uses: NethermindEth/github-workflows/.github/actions/get-group-topic@feat/docker-image-workflow

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

      - name: Login to JFrog
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ inputs.jfrog_url }}
          username: ${{ steps.topics.outputs.group_name }}
          password: ${{ secrets.artifactory_access_token }}

      - name: Set Registry URL and Repo Name
        id: registry
        run: |
          REGISTRY=$(echo "${{ inputs.jfrog_url }}" | sed 's|https://||')
          echo "url=$REGISTRY" >> $GITHUB_OUTPUT
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        if: inputs.promotion_type == ''
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ steps.registry.outputs.url }}/${{ steps.topics.outputs.group_name }}-oci-local-dev/${{ steps.registry.outputs.repo_name }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=raw,value=${{ github.ref_type == 'tag' && github.ref_name || inputs.source_tag }},enable=${{ github.ref_type == 'tag' || inputs.source_tag != '' }}
            type=sha

      - name: Build and Push
        id: build_push
        if: inputs.promotion_type == ''
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Validate Promotion
        if: inputs.promotion_type != ''
        run: |
          if [[ -z "${{ inputs.source_tag }}" ]]; then
            echo "Error: source_tag is required for promotion"
            exit 1
          fi

      - name: Promote to Staging
        if: inputs.promotion_type == 'to-staging' && inputs.source_tag != ''
        run: |
          SOURCE_REPO="${{ steps.topics.outputs.group_name }}-oci-local-dev"
          TARGET_REPO="${{ steps.topics.outputs.group_name }}-oci-local-staging"
          
          REGISTRY="${{ steps.registry.outputs.url }}"
          IMAGE_NAME="${{ steps.registry.outputs.repo_name }}"
          
          # Promote version tag and latest
          for TAG in "${{ inputs.source_tag }}" "latest"; do
            source_image="${REGISTRY}/${SOURCE_REPO}/${IMAGE_NAME}:${TAG}"
            target_image="${REGISTRY}/${TARGET_REPO}/${IMAGE_NAME}:${TAG}"
            echo "Promoting ${source_image} to ${target_image}"
            docker buildx imagetools create -t "${target_image}" "${source_image}"
          done

      - name: Promote to Production
        if: inputs.promotion_type == 'to-prod' && inputs.source_tag != ''
        run: |
          SOURCE_REPO="${{ steps.topics.outputs.group_name }}-oci-local-staging"
          TARGET_REPO="${{ steps.topics.outputs.group_name }}-oci-local-prod"
          
          REGISTRY="${{ steps.registry.outputs.url }}"
          IMAGE_NAME="${{ steps.registry.outputs.repo_name }}"
          
          # Promote version tag and latest
          for TAG in "${{ inputs.source_tag }}" "latest"; do
            source_image="${REGISTRY}/${SOURCE_REPO}/${IMAGE_NAME}:${TAG}"
            target_image="${REGISTRY}/${TARGET_REPO}/${IMAGE_NAME}:${TAG}"
            echo "Promoting ${source_image} to ${target_image}"
            docker buildx imagetools create -t "${target_image}" "${source_image}"
          done

      - name: Record Promotion
        if: inputs.promotion_type == 'to-staging' || inputs.promotion_type == 'to-prod'
        run: |
          echo "## Image Promotion :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- From: ${{ inputs.promotion_type == 'to-staging' && 'dev' || 'staging' }}" >> $GITHUB_STEP_SUMMARY
          echo "- To: ${{ inputs.promotion_type == 'to-staging' && 'staging' || 'production' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Image: ${{ steps.registry.outputs.repo_name }}:${{ inputs.source_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY

      - name: Summary
        if: inputs.promotion_type == ''
        run: |
          echo "## Docker build completed :green_circle:" >> $GITHUB_STEP_SUMMARY
          echo "### Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r TAG; do
            echo "- $TAG" >> $GITHUB_STEP_SUMMARY
          done