name: Create release
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    uses: ./.github/workflows/release-please.yaml
    with:
      releaseType: simple
